[project]
name = 'Personal-Data-Marketplace'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.data-access]
path = 'contracts/data-access.clar'
clarity_version = 2
epoch = 2.5

[contracts.data-ownership]
path = 'contracts/data-ownership.clar'
clarity_version = 2
epoch = 2.5

[contracts.price]
path = 'contracts/price.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
